### ISSUE TITLE
as a source links with .htm dose not redirect to DNN page

### ISSUE THREAD

**Issue by parsa-taheri** [40fingers/DNN-SEORedirect#11]
Dear Sir,
Good for you,

As a source links with .htm dose not redirect to DNN page.

my source link is :  http://www.dadgaran.com/article/131/index.htm

and my Target url  is : https://www.dadgaran.com/نمونه-آرا-حقوقی

but, every link has **.htm**  in extension  can not redirect to my dnn page.

Thank you for your considerations,
Parsa

**Comment by Timo-Breumelhof** [comment]
For ASP.NET an .htm file is a static file and normally not handled by .NET
This means you either have to make sure .NET does handle them, but the easiest way is to set the 404 page for static files to your DNN 404 page.
In that case the module on the 404 page will handle the redirect.
Please read the section in the manual about this and let us know if that works for you.

**Comment by Timo-Breumelhof** [comment]
@parsa-taheri can you let us know if this this helped you or not?

**Comment by parsa-taheri** [comment]
Dear Timo,
Yes, i can.
Thank you for your attention.
Best regards

Best regards,
Parsa Taheri

**Comment by Timo-Breumelhof** [comment]
ok thanks for the feedback
