### ISSUE TITLE
Documentation XML format error

### ISSUE THREAD

**Issue by leedavi** [40fingers/DNN-SEORedirect#15]
IN the documentation, under "Side Effects of logging 404s "

The XML is formatted wrongly.  The starting nodes are ending nodes....

&lt;/rewrite&gt;
 &lt;/rules&gt; 

should be 

&lt;rewrite&gt;
 &lt;rules&gt;

**Comment by Timo-Breumelhof** [comment]
ok thanks for reporting this, i'll fix it. :-)

**Comment by Timo-Breumelhof** [comment]
https://www.40fingers.net/Portals/0/Downloads/Manuals/Manual-40Fingers-SEO-Redirect-20191107.pdf
