### ISSUE TITLE
40F_SEO_RedirectLog cleaning

### ISSUE THREAD

**Issue by Timo-Breumelhof** [40fingers/DNN-SEORedirect#25]
The 40F_SEO_RedirectLog table can grow considerably on an active website.
From a functional perspective it's not a problem to clean the table, you would only reset your "counters"
Could / should we:
A. Add a clean option in the edit interface?
B. Add a auto clean after x days setting?
C. Add another "count" table and push the results of the log table to that table every x period or so?

**Comment by skamphuis** [comment]
We will add the option to use a scheduled task to clean up the log table. For now the following options will be implemented:
- the option to turn cleaning on and off per portal
- remove all log entries older than a given number of days
- remove all log entries except the most recent nnn

**Comment by Tychodewaard** [comment]
@skamphuis how can I utilize this? Is there some documentation on this? The UI seems to be unchanged or am I missing something?

**Comment by skamphuis** [comment]
> @skamphuis how can I utilize this? Is there some documentation on this? The UI seems to be unchanged or am I missing something?

Just have a look at the module settings. You can enable the scheduler there and specify what logs you want removed. I'll add it to the documentation page too, thanks.
