### ISSUE TITLE
Replace the seoredirect.xml file with a table

### ISSUE THREAD

**Issue by EPTamminga** [40fingers/DNN-SEORedirect#27]
I understand that an XML file can be handy to distribute, but a table would prevent a lot of potential problems.
- You can have the right unique keys (like the SourceURL) to prevent duplicates
- It is much easier for reporting (no need to update the log file after a redirect edit)
- Security is handled by default
- No endless backup files of the XML file
The basic additional need would be an import & export facility, which should be that complicated since you have the SourceURL as the unique key next to the PK

**Comment by skamphuis** [comment]
I've thought about the option to switch to a table at some point, and back. That way we could have best of both worlds. But it's not in there for now.

**Comment by EPTamminga** [comment]
I know you do not have the time atm, nevertheless I think a table i.s.o. a file is a better solution.
