### ISSUE TITLE
Different images for different tasks

### ISSUE THREAD

**Issue by EPTamminga** [40fingers/DNN-SEORedirect#4]
Ths current layout uses the same image for adding records and maintaining existing records:

![image](https://user-images.githubusercontent.com/5859855/64767670-5c098480-d548-11e9-97c7-6c3de5b3ce0b.png)

Can we have a **different image** for the records? And split the single image in **separate Edit & Delete** images & actions? So that deleting a record is much easier?

**Comment by Timo-Breumelhof** [comment]
Will be part of 02.03.00
