### ISSUE TITLE
Add a space between checkbox, radiobutton and the label text

### ISSUE THREAD

**Issue by EPTamminga** [40fingers/DNN-SEORedirect#47]
![image](https://user-images.githubusercontent.com/5859855/73467344-7f13c400-4383-11ea-9283-d32c3be34dc5.png)

**Comment by Timo-Breumelhof** [comment]
Hmm, I added some styling for this previously, I'll have a look what went wrong here :-)

**Comment by EPTamminga** [comment]
I submitted a PR to correct this.

**Comment by Timo-Breumelhof** [comment]
Yes I saw that, but I need to make sure that we don't end up with  two corrections for this :-)

**Comment by EPTamminga** [comment]
Mine is OK :-)
