### ISSUE TITLE
Option to get a 404 for non-existant child pages

### ISSUE THREAD

**Issue by skamphuis** [40fingers/DNN-SEORedirect#53]
For example, when you have a page named
/Banana
with no child pages, DNN will allow you to navigate to the page
/Banana/pineapple
even it that doesn't exist. You will just see /Banana

Reason for that is obvious: there might be a module on the page that uses the extra information /pineapple

However, for SEO, we want to be able to get a 404 anyway, when /Banana/pineapple does not exist.

To achieve this, we should be able to specifiy which pages might have "dynamic url's" and which don't.

**Comment by Timo-Breumelhof** [comment]
added to  04.06.00
